# SkyeBlock Configuration
# Default template for nether islands
  default-template: "nether_generic"

# World settings
world:
  name: "skyblock_world"
  environment: "NORMAL"
  # Automatically create nether world
  auto-create-nether: true
  # World border settings
  border:
    enabled: true
    size: 10000
  
# Nether world settings
nether:
  # Nether world name pattern: {main_world_name}_nether
  name-suffix: "_nether"  # Will create "skyblock_world_nether" 
  environment: "NETHER"
  biome: "NETHER_WASTES"
  enabled: true
  # Default template for nether islands
  default-template: "nether_generic"

# Hub world settings
hub:
  world: "hub"
  spawn:
    x: 0
    y: 0
    z: 0
  enabled: true
  
# Island settings
island:
  # Island template types (matching GUI island names)
  templates:
    # Easy Islands (Green difficulty)
    vanilla: "vanilla"
    beginner: "beginner"
    "mossy cavern": "mossy_cavern"
    "farmers dream": "farmers_dream"
    mineshaft: "mineshaft"
    "cozy grove": "cozy_grove"
    "bare bones": "bare_bones"

    # Medium Islands (Yellow difficulty)
    campsite: "campsite"
    "fishermans paradise": "fishermans_paradise"
    inverted: "inverted"
    "grid map": "grid_map"
    "2010": "2010"
    orchid: "orchid"

    # Hard Islands (Red difficulty)
    advanced: "advanced"
    igloo: "igloo"
    "nether jail": "nether_jail"
    desert: "desert"
    wilson: "wilson"
    olympus: "olympus"
    "sandy isle": "sandy_isle"
    
    # Special Nether Template for nether world
    nether_generic: "nether_generic"
  # Default template when creating islands
  default-template: "vanilla"
  # Default nether template for nether world generation
  default-nether-template: "nether_generic"
  
# Server Brand Settings
server-brand:
  # Whether to enable custom server brand
  enabled: true
  # The custom brand name to show in the F3 debug screen
  name: "LegitiSkyeSlimePaper"
  # Whether to send brand updates periodically
  periodic-updates: true
  # Update interval in minutes (will send to all players every X minutes)
  update-interval-minutes: 10

# Messages (using MiniMessage format)
messages:
  prefix: "<dark_gray>[<gold>SkyeBlock</gold>]</dark_gray> "
  island-created: "<green>Island created successfully! Teleporting you there...</green>"
  island-already-exists: "<red>You already have an island!</red>"
  island-not-found: "<red>Island not found!</red>"
  no-permission: "<red>You don't have permission to do that!</red>"
  invalid-template: "<red>Invalid island template! Available templates: <yellow>vanilla</yellow>, <yellow>beginner</yellow>, <yellow>mossy cavern</yellow>, <yellow>famers dream</yellow>, <yellow>mineshaft</yellow>, <yellow>cozy grove</yellow>, <yellow>bare bones</yellow>, <yellow>campsite</yellow>, <yellow>fishermans paradise</yellow>, <yellow>inverted</yellow>, <yellow>grid map</yellow>, <yellow>2010</yellow>, <yellow>advanced</yellow>, <yellow>igloo</yellow>, <yellow>nether jail</yellow>, <yellow>desert</yellow>, <yellow>wilson</yellow>, <yellow>olympus</yellow>, <yellow>sandy isle</yellow></red>"
  teleported: "<green>You have been teleported to your island!</green>"
  invalid-command: "<red>Invalid command! Use <yellow>/island help</yellow> for available commands.</red>"
  island-deleted: "<green>Your island has been deleted! You have been teleported to the hub.</green>"
  teleported-to-hub: "<green>You have been teleported to the hub!</green>"
  hub-not-configured: "<red>Hub world is not properly configured!</red>"
  help-header: "<gold><bold>===== SkyeBlock Commands =====</bold></gold>"
  help-create: "<yellow>/island create [type]</yellow> - <gray>Create a new island (19 types available)</gray>"
  help-create-nether: "<yellow>/island create nether</yellow> - <gray>Create a nether portal island in the nether dimension</gray>"
  help-teleport: "<yellow>/island tp</yellow> - <gray>Teleport to your island</gray>"
  help-delete: "<yellow>/island delete</yellow> - <gray>Delete your island</gray>"
  help-list: "<yellow>/island list</yellow> - <gray>List available island types</gray>"
  help-hub: "<yellow>/hub</yellow> - <gray>Teleport to the hub world</gray>"
  
# Schematic settings
schematics:
  # Path where island templates are stored
  template-path: "plugins/SkyeBlock/schematics/"
