#do not change
version: 2.0.0

# SkyeBlock Configuration

# Hub world settings (teleportation destination - uses existing world)
hub:
  # Name of the existing world to teleport players to (e.g., "world", "lobby", "spawn")
  world: "spawn"
  # Spawn coordinates within the hub world
  spawn:
    x: 0.5
    y: 62
    z: 0.5
    # Yaw (horizontal rotation: 0=south, 90=west, 180=north, 270=east)
    yaw: -90.0
    # Pitch (vertical rotation: -90=up, 0=straight, 90=down)
    pitch: 0.0
  # Whether hub teleportation is enabled
  enabled: true
  # Whether to teleport players to hub when they join the server
  teleport-on-join: true

# World settings (not used - individual worlds created per island)
world:
  name: "skyblock_world"
  environment: "NORMAL"
  # Note: Auto-create-nether disabled - resource worlds managed separately
  auto-create-nether: true
  # World border settings (applied to individual island worlds)
  border:
    enabled: true
    size: 10000
  
# Resource world settings (managed by ResourceWorldManager)
resource-worlds:
  nether:
    path: "skyeblock/resource/nether"
    environment: "NETHER"
    biome: "NETHER_WASTES"
    enabled: false
    # Default template for nether islands
    default-template: "nether_generic"
  end:
    path: "skyeblock/resource/end"
    environment: "THE_END"
    enabled: true 
  
# Island settings
island:
  # Whether to teleport players to their island when they join the server (if they have one)
  # If false or if they don't have an island, they'll be teleported to hub/spawn instead
  teleport-to-island-on-join: false
  # Island creation cooldown settings
  create-island:
    # Time in seconds to wait before allowing new island creation after deletion (1 hour)
    delay: 3600
    # Maximum number of times a player can delete and recreate islands
    tries: 3
  # Island template types (matching GUI island names)
  templates:
    # Easy Islands (Green difficulty)
    classic: "vanilla"
    vanilla: "vanilla"
    beginner: "beginner"
    "mossy cavern": "mossy_cavern"
    "farmers dream": "farmers_dream"
    mineshaft: "mineshaft"
    "cozy grove": "cozy_grove"
    "bare bones": "bare_bones"

    # Medium Islands (Yellow difficulty)
    campsite: "campsite"
    "fishermans paradise": "fishermans_paradise"
    inverted: "inverted"
    "grid map": "grid_map"
    "2010": "2010"
    orchid: "orchid"

    # Hard Islands (Red difficulty)
    advanced: "advanced"
    igloo: "igloo"
    "nether jail": "nether_jail"
    desert: "desert"
    wilson: "wilson"
    olympus: "olympus"
    "sandy isle": "sandy_isle"
    
    # Special Nether Template for nether world
    nether_generic: "nether_generic"
  # Default template when creating islands
  default-template: "vanilla"
  # Default nether template for nether world generation
  default-nether-template: "nether_generic"
  
  # Island visiting settings
  visiting:
    # Whether island visiting is enabled globally
    enabled: false

# Messages (using MiniMessage format)
messages:
  prefix: "<dark_gray>[<gold>SkyeBlock</gold>]</dark_gray> "
  island-created: "<green>Island created successfully! Teleporting you there...</green>"
  island-already-exists: "<red>You already have an island!</red>"
  island-not-found: "<red>Island not found!</red>"
  no-permission: "<red>You don't have permission to do that!</red>"
  invalid-template: "<red>Invalid island template! Available templates: <yellow>vanilla</yellow>, <yellow>beginner</yellow>, <yellow>mossy cavern</yellow>, <yellow>farmers dream</yellow>, <yellow>mineshaft</yellow>, <yellow>cozy grove</yellow>, <yellow>bare bones</yellow>, <yellow>campsite</yellow>, <yellow>fishermans paradise</yellow>, <yellow>inverted</yellow>, <yellow>grid map</yellow>, <yellow>2010</yellow>, <yellow>orchid</yellow>, <yellow>advanced</yellow>, <yellow>igloo</yellow>, <yellow>nether jail</yellow>, <yellow>desert</yellow>, <yellow>wilson</yellow>, <yellow>olympus</yellow>, <yellow>sandy isle</yellow></red>"
  teleported: "<green>You have been teleported to your island!</green>"
  invalid-command: "<red>Invalid command! Use <yellow>/island help</yellow> for available commands.</red>"
  island-deleted: "<green>Your island has been deleted! You have been teleported to the hub.</green>"
  teleported-to-hub: "<green>You have been teleported to the hub!</green>"
  hub-not-configured: "<red>Hub world is not properly configured!</red>"
  help-header: "<gold><bold>===== SkyeBlock Commands =====</bold></gold>"
  help-create: "<yellow>/island create [type]</yellow> - <gray>Create a new island (19 types available)</gray>"
  help-create-nether: "<yellow>/island create nether</yellow> - <gray>Create a nether portal island in the nether dimension</gray>"
  help-teleport: "<yellow>/island tp</yellow> - <gray>Teleport to your island</gray>"
  help-delete: "<yellow>/island delete</yellow> - <gray>Delete your island</gray>"
  help-list: "<yellow>/island list</yellow> - <gray>List available island types</gray>"
  help-hub: "<yellow>/hub</yellow> - <gray>Teleport to the hub world</gray>"
  cooldown-active: "<red>You must wait {time} before creating a new island.</red>"
  max-tries-reached: "<red>You have reached the maximum number of island deletions ({tries}). You cannot create new islands.</red>"
  deletion-warning: "<yellow>Warning: You have {remaining} deletion(s) remaining before cooldown restriction applies.</yellow>"
  deletion-blocked-cooldown: "<red>You cannot delete your island while on cooldown. Time remaining: {time}</red>"
  deletion-requires-island-location: "<red>You must be on your island to delete it during cooldown period!</red>"
  deletion-cooldown-info: "<yellow>You have made {current} deletions. You must wait {time} before being able to delete your next island.</yellow>"
  
# Schematic settings
schematics:
  # Path where island templates are stored
  template-path: "schematics/"
